name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        run: docker build -t myapp-backend:${{ github.ref_name }} -f backend/Dockerfile.backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t myapp-frontend:${{ github.ref_name }} -f frontend/Dockerfile.frontend ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker Image
        run: docker push myapp-backend:${{ github.ref_name }}

      - name: Push Frontend Docker Image
        run: docker push myapp-frontend:${{ github.ref_name }}

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on main branch

    steps:
      - name: SSH and deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/deploy
            docker-compose pull
            docker-compose up -d --build
